// Must run before any app module import (listed first in vitest setupFiles).
process.env.NODE_ENV = 'test'
process.env.PORT = '5000'
process.env.MONGODB_URI = process.env.MONGODB_URI || 'mongodb://127.0.0.1:27017/veolms-test'
process.env.REDIS_URL = process.env.REDIS_URL || 'redis://127.0.0.1:6379'
process.env.JWT_ACCESS_SECRET = 'test-jwt-access-secret-minimum-32-characters-long'
process.env.JWT_REFRESH_SECRET = 'test-jwt-refresh-secret-minimum-32-characters-long'
process.env.ENCRYPTION_KEY = '0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef'
process.env.RAZORPAY_KEY_ID = 'rzp_test_xxx'
process.env.RAZORPAY_KEY_SECRET = 'xxx'
process.env.FRONTEND_URL = 'http://localhost:5173'
process.env.R2_ACCOUNT_ID = 'test-account'
process.env.R2_ACCESS_KEY_ID = 'test-access-key'
process.env.R2_SECRET_ACCESS_KEY = 'test-secret-key'
process.env.R2_BUCKET_NAME = 'veo-lms-test'
process.env.R2_ENDPOINT = 'https://test-account.r2.cloudflarestorage.com'
process.env.R2_PUBLIC_URL = 'https://pub-test.r2.dev'
