name: Sync Production Repository

on:
  push:
    branches:
      - prod

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: prod
          fetch-depth: 0

      - name: Push to Production Repository
        env:
          PROD_PAT: ${{ secrets.PROD_PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git remote add production https://x-access-token:${PROD_PAT}@github.com/globalsuccess080-afk/veo-lms.git

          git push production HEAD:main --force
